import {Link} from 'react-router-dom';
const Support=()=> <a href="mailto:info@themomentumrule.com">info@themomentumrule.com</a>;
export function Privacy(){return <main className="app-container"><h1>Momentum60 privacy</h1><p>Updated 3 October 2026. This policy covers the Momentum60 app and its web version, operated by Wild Hearts Publishing Pty Ltd (ABN 34 695 911 025). Contact <Support/>.</p>
 <section><h2>Information you choose to save</h2><p>We process your account email and authentication details, your practice and its cue, recorded actions, optional journal reflections, archived seasons, timezone, reminder preferences and consent choices. Supabase provides account and database services. Your password is handled by its authentication service; do not send it to support.</p><p>We use this information to provide your programme, synchronise your saved records, recover drafts and respond to account requests. Your journal is not published or shared with a partner. Partner sharing is unavailable in this release.</p></section>
 <section><h2>Subscriptions and service providers</h2><p>Apple or Google processes native purchases. Your app account identifier is attached to a store purchase, and we verify the purchase directly with Apple or Google so we can confirm access and restore purchases. Website subscriptions use Stripe. We receive subscription and transaction information, not your complete card details.</p><p>Vercel hosts the web app and service endpoints. Hosting and service providers may process connection information, including IP addresses and service logs, to operate and protect their services. Providers may process information outside your country. The app streams music from our website and may load fonts or legacy images from external providers, which receive the connection information needed to deliver them.</p></section>
 <section><h2>Copies on this device</h2><p>The app stores an authentication session, preferences, cached programme history and unsaved journal drafts on this device. Drafts are not an online backup. Signing out removes this account’s cached history and drafts from this device. Completing account deletion also clears these copies on the device where you delete the account. Other offline devices cannot receive a deletion update until they reconnect; sign out or remove the app on any other device you used.</p></section>
 <section><h2>Your choices and deletion</h2><p>Reflections and reminders are optional. The core service does not require advertising tracking. We do not sell your journal or use it for advertising. You can read your saved history after your subscription ends.</p><p>We keep your active account and programme records until you delete the account. In-app deletion removes your authentication account and programme records from the active database. Billing providers may retain transaction records for payment administration, refunds and their legal obligations. Backups and security logs may persist under the providers’ retention schedules; contact us for information about a specific deletion request.</p><p><Link to="/delete-account">Request account and associated-data deletion</Link>, or contact <Support/> for access, correction or privacy questions. Apple and Google subscription cancellation is separate from account deletion.</p></section>
 <section><h2>Children and changes</h2><p>Momentum60 is not directed at children. If you are under 16, involve a parent or guardian before creating an account. We will update this page when the app’s data practices change.</p></section><p><Link to="/terms">Subscription terms</Link></p></main>}
export function Terms(){return <main className="app-container"><h1>Momentum60 subscription terms</h1><p>Updated 3 October 2026. The service is provided by Wild Hearts Publishing Pty Ltd (ABN 34 695 911 025). Questions: <Support/>.</p>
 <section><h2>Your subscription</h2><p>A monthly subscription provides the 60-day programme, album, journal and repeat seasons. Website pricing is A$4.99 per month. For an Apple or Google purchase, the store displays the applicable price and currency before confirmation. Subscriptions renew monthly until cancelled with the provider where you bought them.</p><p>The programme length is separate from the billing period. Sixty days can cross more than two billing dates. Pausing the programme does not pause or cancel billing. Repeat seasons reuse the programme and album; new monthly material, coaching and personal-song production are not included.</p></section>
 <section><h2>Cancellation, refunds and account deletion</h2><p>Use Settings and billing to identify your provider and manage renewal. Paid access continues through the paid period after cancellation, subject to refunds or revoked transactions. Saved history remains readable after paid access ends. Store purchases are handled by Apple or Google under their payment and refund processes. For website billing help, contact us.</p><p>Deleting your account removes its programme records and login. Website renewals are cancelled as part of successful deletion. Apple and Google renewals must be cancelled in the relevant store account; deleting the app or app account does not cancel them. Our <Link to="/delete-account">deletion page</Link> explains both paths.</p></section>
 <section><h2>Using the programme</h2><p>This is a personal practice and reflection service, not medical or psychological treatment. Choose actions suitable for your circumstances. There is no guaranteed health, financial or personal outcome. Music and journaling are optional.</p><p>Keep your login private. Your personal subscription does not grant permission to redistribute recordings or other protected content. Earlier participants retain access and earned rewards according to their original offer; those rewards are not part of a new subscription.</p></section>
 <section><h2>Your rights</h2><p>Nothing here excludes rights that cannot be excluded under applicable consumer law, including Australian Consumer Law. Contact us if the service does not work as described. These terms operate alongside the applicable store terms and our <Link to="/privacy">privacy policy</Link>.</p></section></main>}
export function DeleteAccount(){return <main className="app-container"><h1>Delete your Momentum60 account</h1><p>You can request deletion without reinstalling the app. This applies to Momentum60 accounts operated by Wild Hearts Publishing Pty Ltd.</p>
 <section><h2>From the app or web app</h2><ol><li>Sign in and open Settings and billing.</li><li>Review the subscription provider. Cancel Apple or Google renewal in that store if you want it to stop.</li><li>Find Delete my account, type DELETE and confirm.</li></ol><p><Link to="/settings">Open Settings and billing</Link></p></section>
 <section><h2>Without signing in</h2><p>Email <a href="mailto:info@themomentumrule.com?subject=Momentum60%20account%20deletion">info@themomentumrule.com</a> from the email address used for your account, with the subject “Momentum60 account deletion”. We will verify ownership before deleting it. If you cannot access that email address, contact the same address for help. Do not include your password or journal entries.</p><p>A sent email is a deletion request, not confirmation that deletion has finished. We will confirm the outcome by email.</p></section>
 <section><h2>What deletion removes</h2><p>Your login, practice, progress, reflections, custom rules and archived seasons are removed from the active service. This cannot be undone. Local drafts and cached history are cleared on the device where in-app deletion completes. Sign out or remove the app from any other devices you used. Billing records, security logs and backups may be retained as explained in our <Link to="/privacy">privacy policy</Link>.</p><p>Apple and Google billing are separate. Account deletion does not cancel those renewals. Use <a href="https://apps.apple.com/account/subscriptions">Apple subscription settings</a> or <a href="https://play.google.com/store/account/subscriptions">Google Play subscription settings</a>. Website renewals are cancelled as part of successful account deletion.</p></section></main>}
