// Presence checks only. Never print credential values.
const required=['SUPABASE_URL','SUPABASE_SERVICE_ROLE_KEY','STRIPE_SECRET_KEY','STRIPE_MONTHLY_PRICE_ID','STRIPE_WEBHOOK_SECRET','NATIVE_PRODUCT_IDS','APPLE_APP_ID','GOOGLE_PLAY_SERVICE_ACCOUNT_JSON','CRON_SECRET','VITE_SUPABASE_URL','VITE_SUPABASE_ANON_KEY','VITE_NATIVE_PRODUCT_ID','VITE_ANDROID_BASE_PLAN_ID','VITE_API_ORIGIN'];
let failed=false;for(const key of required){const okay=Boolean(process.env[key]?.trim());console.log(`${okay?'PASS':'MISSING'} ${key}`);failed||=!okay;}
if(process.env.BILLING_ENV!=='production'){console.log('BLOCKED BILLING_ENV must be production for a public release');failed=true;}
if(process.env.STRIPE_SECRET_KEY&&!process.env.STRIPE_SECRET_KEY.startsWith('sk_live_')){console.log('BLOCKED Stripe live key is required for a public release');failed=true;}
if(process.env.APPLE_APP_ID&&!/^\d+$/.test(process.env.APPLE_APP_ID)){console.log('BLOCKED APPLE_APP_ID must be the numeric Apple ID from App Store Connect');failed=true;}
if(process.env.NATIVE_PRODUCT_IDS&&process.env.VITE_NATIVE_PRODUCT_ID&&!process.env.NATIVE_PRODUCT_IDS.split(',').map(id=>id.trim()).includes(process.env.VITE_NATIVE_PRODUCT_ID)){console.log('BLOCKED VITE_NATIVE_PRODUCT_ID is not among the server-approved NATIVE_PRODUCT_IDS');failed=true;}
console.log('Native review transactions: Apple-signed sandbox transactions and Google Play test purchases are accepted; Xcode local test-store transactions are rejected. Set the App Store Server Notifications (version 2) URL to /api/apple-notifications for production and sandbox.');
console.log('Manual gates: sandbox purchase/restore/refund, live migrations, physical devices, signed store builds, privacy declarations, legal pricing, content rights. Presence is not verification.');process.exitCode=failed?1:0;
